name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
env:
  doc_user: ${{ secrets.DOCKER_USER }}
  doc_pd: ${{ secrets.DOCKER_PASSWORD }}

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: docker login
      run: |
        docker login -u $doc_user -p $doc_pd
    - name : docker build
      run: |
        docker build --platform linux/amd64 -t $doc_user/hangman:latest .
    - name : docker push
      run: docker push $doc_user/hangman:latest
